# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
meta_title: Edward Meehan
meta_desc: This is the site description.

title: Edward Meehan #displayed on site header
subtitle: Conversion Specialist  #displayed on site header

address: 123 Test st. San Diego, CA 92115-1234
phone: 555.555.5555
email: edward.meehan.808@gmail.com

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://emeehan.com" # the base hostname & protocol for your site
debugmode: false

# Build settings
markdown: kramdown
error_mode: warn
plugins: [github-pages]
exclude: ['node_modules','package.json','emeehan.sublime-project','package-lock.json','Gemfile','Gemfile.lock','README.md','webpack','webpack.config.js']
# include: 
# keep_files:
# timezone:
# encoding:

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Defaults
defaults:
  -
    scope:
      path: ''
      type: 'pages'
    values:
      block_top: false
      block_bottom: false
      block_header: header.html
      block_footer: footer.html