# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Edward Meehan
description: This is the default site description here. 

phone: 555.555.5555

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://emeehan.com" # the base hostname & protocol for your site
js_scripts: [
  "/js/main.js",
  "/js/contact_form.js"
]
css_styles: [
  "https://fonts.googleapis.com/css?family=Roboto+Slab|Noto+Sans:400,700",
  "https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.min.css",
  "/css/2019.css"
]

gtm_container_id:

# Build settings
markdown: kramdown
error_mode: warn
plugins: [github-pages]
exclude: ['node_modules','package.json','emeehan.sublime-project','package-lock.json','Gemfile','Gemfile.lock','README.md','webpack','webpack.config.js']
  # include: 
  # keep_files:
  # timezone:
  # encoding:

# Sass
sass:
  sass_dir: _sass
  #style: compressed

# Projects
collections:
  
  projects:
    output: true
  
  posts_categories:
    output: true

# Defaults
defaults:
  -
    scope:
      path: ''
    values:
      js_scripts: []
      css_styles: ["/css/backgrounds-blue.css"]
      color_style: theme--blue
      color_background_count: 7
      layout: 2019_default
      #layout_id: default-layout -- default set in layout file
  -
    scope:
      path: ''
      type: pages
    values:
      title: this is the default page title here.
      description: This is the default page description here.
      og-image: /img/open-graph-image.png
      #permalink: /:path/:basename:output_ext
  -
    scope:
      path: ''
      type: posts
    values:
      permalink: /blog/:categories/:title
      css_styles: ["/css/backgrounds-black.css","/css/blog.css"]
      color_style: theme--black
      color_background_count: 2
  -
    scope:
      path: ''
      type: posts_categories
    values:
      permalink: /blog/:name
      css_styles: ["/css/backgrounds-black.css","/css/blog.css"]
      color_style: theme--black
      color_background_count: 2
  -
    scope:
      path: ''
      type: projects
    values:
      permalink: /:collection/:categories/:name
      js_scripts: ["/js/projects.js"]
      css_styles: ["/css/backgrounds-black.css","/css/projects.css"]
      color_style: theme--black
      color_background_count: 2
      layout: 2019_project_page
      comments: true

