# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://emeehan.com" # the base hostname & protocol for your site

# Meta settings
title: Edward Meehan
description: This is the default site description here. 
js_scripts:
  - 
    path: /js/main.js
    cache_bust: true
    absolute_url: true
  -
    path: /js/contact_form.js
    cache_bust: true
    absolute_url: true
css_styles:
  -
    path: https://fonts.googleapis.com/css?family=Roboto+Slab|Noto+Sans:400,700
  -
    path: https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.min.css
  -
    path: /css/2019.css
    cache_bust: true
    absolute_url: true
gtm_container_id:

# General information
phone: 1-858-876-8088

# Configuration options - https://jekyllrb.com/docs/configuration/options/
markdown: kramdown
error_mode: warn
plugins:
  - github-pages
  # - jekyll-redirect-from
exclude:
  - node_modules
  - package.json
  - emeehan.sublime-project
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - README.md
  - webpack
  - webpack.config.js

# Sass - https://jekyllrb.com/docs/assets/#sassscss
sass:
  sass_dir: _sass
  style: compressed

# Collections - https://jekyllrb.com/docs/collections/
collections:
  projects:
    output: true
  posts_categories:
    output: true

# Defaults - https://jekyllrb.com/docs/configuration/front-matter-defaults/
defaults:
  -
    scope:
      path: ''
    values:
      layout: 2019_default
      theme_color: blue
      og-image: /img/open-graph-image.png
      description: This is the default page description here.
      share: true
      #layout_id: default-layout -- default set in layout file
      #js_scripts:
      #css_styles:
      #comments:
      #image:
      #share:
  -
    scope:
      path: ''
      type: pages
    values:
      title: this is the default page title here.
      description: This is the default page description here.
  -
    scope:
      path: ''
      type: posts
    values:
      permalink: /blog/:categories/:title
      layout: 2019_blog_post
      comments: true
      excerpt_separator: <!--more-->
      css_styles:
        -
          path: /css/blog.css
          cache_bust: true
          absolute_url: true
  -
    scope:
      path: ''
      type: posts_categories
    values:
      permalink: /blog/:name/
      theme_color: black
      css_styles:
        -
          path: /css/blog.css
          cache_bust: true
          absolute_url: true
  -
    scope:
      path: ''
      type: projects
    values:
      permalink: /:collection/:categories/:title
      theme_color: black
      layout: 2019_project_page
      comments: true
      css_styles:
        -
          path: /css/projects.css
          cache_bust: true
          absolute_url: true
