# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Edward Meehan | Front-End Web Developer
email: edward.meehan.808@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://emeehan.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
error_mode: warn
plugins: [github-pages]
exclude: ['node_modules','package.json','emeehan.sublime-project','package-lock.json','Gemfile','Gemfile.lock','README.md','webpack','webpack.config.js']
# include: 
# keep_files:
# timezone:
# encoding:

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Defaults
defaults:
  -
    scope:
      path: ''
      type: 'pages'
    values:
      skin: 'default'
      blockName: 'content'